#!/bin/bash

#files=uc15_1500md_15sig.gdx
#for file in $files
for i in {1500..4500..1000}
do
for j in {15..25..5}
do
	file=uc15_${i}md_${j}sig.gdx
	mkdir lb_${file%%.*}
	cd lb_${file%%.*}
	cp ~/jim_master_code/data/gen15/$file .
	cp ~/jim_master_code/code/lb_main.m .
	cp ~/jim_master_code/code/per_info_mip.gms .
	cp ~/jim_master_code/code/max_Lg_r_d.m .
	cp ~/jim_master_code/code/max_Lg_r.m .
	cp ~/jim_master_code/code/Lg_r_d.m .
	cp ~/jim_master_code/code/Lg_r.m .
	cp ~/jim_master_code/code/Lg_d.m .
	cp ~/jim_master_code/code/Lg.m .
	cp ~/jim_master_code/code/eval_pwl.m .
	cp ~/jim_master_code/code/lp_power.m .
	cp ~/jim_master_code/code/gendist.m .
	cp ~/jim_master_code/code/startup.m .
	cp ~/jim_master_code/code/Lg_condor.run .
	cp ~/jim_master_code/code/condor_gams_8CPU_4MEM_12DISK .

        echo "lb_main('${file%%.*}',250,50/${i},(0.99).^(0:249))" > script.m
#        echo "lb_main('${file%%.*}',1,50/${i},(0.99).^(0))" > script.m
        export REQUEST_CPUS=4
 
	./condor_gams_8CPU_4MEM_12DISK Lg_condor.run "script.m,lb_main.m,per_info_mip.gms,max_Lg_r_d.m,max_Lg_r.m,Lg_r_d.m,Lg_r.m,Lg_d.m,Lg.m,eval_pwl.m,lp_power.m,gendist.m,startup.m,$file" &
	cd ..
done
done
