#!/bin/bash

#files=uc15_1500md_15sig.gdx
#for file in $files
for i in {4..8..2}
do
for j in {15..25..5}
do
	file=uc15_${i}md_${j}sig.gdx
	cd ub_${file%%.*}
	cp init_expdem_$file ~/dual-adp-suc/data/gen15/.
	cd ..
done
done
