#!/bin/bash

#files=uc15_1500md_15sig.gdx
#for file in $files
for i in {4..8..2}
do
for j in {15..25..5}
do
	file=uc15_${i}md_${j}sig
	mkdir ub_fv_mip_$file
	cd ub_fv_mip_$file
	cp ~/dual-adp-suc/numerical_runs/gen15/lb_bounds/lb_${file}/max_Lg_r_d_${file}.mat .
	cp ~/dual-adp-suc/code/startup.m .
	cp ~/dual-adp-suc/code/compute_ub_fv_mip.m .
	cp ~/dual-adp-suc/code/ub_fv_mip.gms .
	cp ~/dual-adp-suc/data/gen15/${file}.gdx .
	cp ~/dual-adp-suc/code/Lg_condor.run .
	cp ~/dual-adp-suc/code/condor_gams .

        echo "[ub_cost,ub_time,optca_mat,modelstat_mat,tot_run_time] = compute_ub_fv_mip('$file'); save ub_fv_${file};" > script.m
#        echo "[best_cost,best_idx,opt_cost_vec,time,tot_time,L_g_cost,z_sol_avg,z_sol_std] = max_Lg_r_d('$file',1,50/${i},(0.99).^(0))" > script.m
        export REQUEST_CPUS=4
 
	./condor_gams Lg_condor.run "script.m,compute_ub_fv_mip.m,ub_fv_mip.gms,startup.m,max_Lg_r_d_${file}.mat,${file}.gdx" &
	cd ..
done
done
