#!/bin/bash

#files=uc15_1500md_15sig.gdx
#for file in $files
for i in {4..8..2}
do
for j in {15..25..5}
do
	file=uc15_${i}md_${j}sig.gdx
	mkdir lb_${file%%.*}
	cd lb_${file%%.*}
	cp ~/dual-adp-suc/data/gen15/$file .
	cp ~/dual-adp-suc/code/lb_main.m .
	cp ~/dual-adp-suc/code/per_info_mip_single.gms .
	cp ~/dual-adp-suc/code/run_per_info_mip.m .
	cp ~/dual-adp-suc/code/max_Lg_r_d.m .
	cp ~/dual-adp-suc/code/max_Lg_r.m .
	cp ~/dual-adp-suc/code/Lg_r_d.m .
	cp ~/dual-adp-suc/code/Lg_r.m .
	cp ~/dual-adp-suc/code/Lg_d.m .
	cp ~/dual-adp-suc/code/Lg.m .
	cp ~/dual-adp-suc/code/eval_pwl.m .
	cp ~/dual-adp-suc/code/lp_power.m .
	cp ~/dual-adp-suc/code/gendist.m .
	cp ~/dual-adp-suc/code/startup.m .
	cp ~/dual-adp-suc/code/Lg_condor.run .
	cp ~/dual-adp-suc/code/condor_gams_8CPU_4MEM_12DISK .

        # 15 gen has maxDemand = 4660
        # 30 gen has maxDemand = 6286.2
        # 50 gen has maxDemand = 10184.4
        # it changed!! below are new maxDemands
        # 15 gen has maxDemand = 3479
        # 30 gen has maxDemand = 6017.1
        # 50 gen has maxDemand = 9434.3
        # Use rho = 50 / (0.4 * maxDemand)
        echo "lb_main('${file%%.*}',250,50/(${i}*0.1*4660),(0.99).^(0:249))" > script.m
#        echo "lb_main('${file%%.*}',1,50/${i},(0.99).^(0))" > script.m
        export REQUEST_CPUS=4
 
	./condor_gams_8CPU_4MEM_12DISK Lg_condor.run "script.m,lb_main.m,per_info_mip_single.gms,run_per_info_mip.m,max_Lg_r_d.m,max_Lg_r.m,Lg_r_d.m,Lg_r.m,Lg_d.m,Lg.m,eval_pwl.m,lp_power.m,gendist.m,startup.m,$file" &
	cd ..
done
done
